# Camera settings
camera:
  index: 0  # Default camera (0 is usually built-in webcam)
  width: 1080
  height: 1080

# Face detection settings
face_detection:
  scale_factor: 1.3
  min_neighbors: 5
  min_size: [30, 30]

# Training settings
training:
  samples_needed: 120

# File paths
paths:
  cascade_file: "cascade.xml"
  image_dir: "./images"
  names_file: "./names.json"
  model_version_file: "./model_version.txt"
  model_file: "./model.pth"
