name: Docker deploy

on:
  push:
    branches:
      - main
      - new-model-updates
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t mlops-project-1:latest .

      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Tag Docker image
        run: docker tag mlops-project-1:latest ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-project-1:latest

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-project-1:latest
        
      - name: Connect to the server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -o StrictHostKeyChecking=no << 'EOF'
            if [ ! -d "/home/${{ secrets.SSH_USER }}/mlops-project" ]; then
              mkdir /home/${{ secrets.SSH_USER }}/mlops-project
            fi
            cd /home/${{ secrets.SSH_USER }}/mlops-project
            docker stop mlops-project || true
            docker rm mlops-project || true
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-project-1:latest
            docker run -d -p 2704:8000 \
            --name mlops-project \
            -v ~/.ssh:/root/.ssh \
            -e GIT_SSH_COMMAND="ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no" \
            ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-project-1:latest
          EOF